// gen-examples — Read examples/*.dsl files and generate web/examples.js
//
// Usage: go run scripts/gen-examples/main.go
//
// Scans the examples/ directory, extracts titles from first ! comment
// lines (or derives from filename as fallback), and writes a JS module
// defining const EXAMPLES = [...] with all content embedded.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	repoRoot := findRepoRoot()
	examplesDir := filepath.Join(repoRoot, "examples")
	outFile := filepath.Join(repoRoot, "web", "examples.js")

	entries, err := os.ReadDir(examplesDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading examples/: %v\n", err)
		os.Exit(1)
	}

	type example struct {
		filename string
		title    string
		content  string
	}
	var examples []example

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".dsl") {
			continue
		}
		path := filepath.Join(examplesDir, e.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error reading %s: %v\n", e.Name(), err)
			os.Exit(1)
		}
		content := string(data)
		title := extractTitle(content, e.Name())
		examples = append(examples, example{
			filename: e.Name(),
			title:    title,
			content:  content,
		})
	}

	sort.Slice(examples, func(i, j int) bool {
		return examples[i].filename < examples[j].filename
	})

	seen := map[string]int{}
	for i, ex := range examples {
		if firstIdx, ok := seen[ex.title]; ok {
			suffix := distinguishingSuffix(examples[firstIdx].filename, ex.filename)
			examples[i].title = ex.title + " (" + suffix + ")"
		}
		seen[ex.title] = i
	}

	var b strings.Builder
	b.WriteString("// Auto-generated by scripts/gen-examples — do not edit by hand\n")
	b.WriteString("// Run: go run scripts/gen-examples/main.go\n\n")
	b.WriteString("const EXAMPLES = [\n")

	for _, ex := range examples {
		b.WriteString("  {\n")
		b.WriteString(fmt.Sprintf("    title: %s,\n", jsString(ex.title)))
		b.WriteString(fmt.Sprintf("    filename: %s,\n", jsString(ex.filename)))
		b.WriteString("    content: `")
		b.WriteString(escapeTemplateLit(ex.content))
		b.WriteString("`\n")
		b.WriteString("  },\n")
	}

	b.WriteString("];\n")

	if err := os.WriteFile(outFile, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outFile, err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s (%d examples)\n", outFile, len(examples))
}

func extractTitle(content, filename string) string {
	lines := strings.Split(content, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "! ") {
			rest := strings.TrimPrefix(line, "! ")
			for _, sep := range []string{" — ", " -- "} {
				if idx := strings.Index(rest, sep); idx > 0 {
					return strings.TrimSpace(rest[:idx])
				}
			}
			return rest
		}
		break
	}
	return titleFromFilename(filename)
}

func titleFromFilename(filename string) string {
	s := strings.TrimSuffix(filename, ".dsl")
	s = strings.ReplaceAll(s, "_", " ")
	s = strings.ReplaceAll(s, "-", " ")
	words := strings.Fields(s)
	for i, w := range words {
		if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + w[1:]
		}
	}
	return strings.Join(words, " ")
}

func distinguishingSuffix(baseFilename, dupFilename string) string {
	base := strings.TrimSuffix(baseFilename, ".dsl")
	dup := strings.TrimSuffix(dupFilename, ".dsl")

	var longer, shorter string
	if len(dup) >= len(base) {
		longer, shorter = dup, base
	} else {
		longer, shorter = base, dup
	}

	if strings.HasSuffix(longer, shorter) {
		extra := strings.TrimSuffix(longer, shorter)
		extra = strings.TrimRight(extra, "-_")
		return titleFromFilename(extra + ".dsl")
	}
	if strings.HasPrefix(longer, shorter) {
		extra := strings.TrimPrefix(longer, shorter)
		extra = strings.TrimLeft(extra, "-_")
		return titleFromFilename(extra + ".dsl")
	}

	return titleFromFilename(longer + ".dsl")
}

func jsString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	return "'" + s + "'"
}

func escapeTemplateLit(s string) string {
	s = strings.ReplaceAll(s, "`", "\\`")
	s = strings.ReplaceAll(s, "${", "\\${")
	return s
}

func findRepoRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		dir = "."
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fmt.Fprintln(os.Stderr, "error: go.mod not found")
			os.Exit(1)
		}
		dir = parent
	}
}
