// Auto-generated by scripts/gen-examples — do not edit by hand
// Run: go run scripts/gen-examples/main.go

const EXAMPLES = [
  {
    title: 'Canon in D',
    filename: 'canon-in-d.dsl',
    content: `! Canon in D — Johann Pachelbel (c. 1680)
! Key: D major (2 sharps: F#, C#) | Meter: 4/4
! Ground bass + canon melody
KD M4/4 //d - - -
//a - - -
//b - - -
//#f - - -
//g - - -
//d - - -
//g - - -
//a - - -
! Canon melody — 8th notes, with / to keep in treble range
^#f a d #f a d #f /a
e a #c e a e #c /a
d #f b d #f b d /#f
#c e #f e #c e #f a
g b d g a b /#c d
#f a d #f a d /a /#f
g b d /g a b #c d
#c e a a g #f e d
`
  },
  {
    title: 'Die Gedanken Sind Frei',
    filename: 'die-gedanken-sind-frei.dsl',
    content: `KC M3/4
gg - -
2c--d ec
g - e
g f d
f e g
2c--d ec
g - e
g f d
d c ^c
b 2d--b
c e c
b 2d--b
c e c
2a--b ca
g c eg
f d b
c - -
`
  },
  {
    title: 'Frère Jacques',
    filename: 'frere-jacques.dsl',
    content: `! Frère Jacques — Traditional French Round
! Key: C major | Meter: 4/4
! Voice 1 leads; voice 2 enters 2 bars later
KC M4/4 c d e c :L Fre re Jac ques,
c d e c         :L Fre re Jac ques,
e f g -         :L Dor mez vous?
e f g -         :L Dor mez vous
ga gf e c       :L Sonnez les_ma tin ne.
^ga gf e c      :L Sonnez les_ma tin ne.
c g c -         :L Din, din, don,
c g c -         :L Din, din, don,`
  },
  {
    title: 'God Save The King',
    filename: 'god-save-the-king.dsl',
    content: `KG M3/4
^g g g
2f--g a
b b c
2a--a b
a 2f--g
g - -
g g g
2f--g a
b b c
2a--a b
a 2f--g
g - -
^d d d
2d--c b
c c c
2c--b a
b cb ag
2b--c d
e 2/a--g
g - -
`
  },
  {
    title: 'Greensleeves',
    filename: 'greensleeves.dsl',
    content: `! Greensleeves — Traditional English Folk Song
! Key: E minor (relative to G major, 1 sharp) | Meter: 6/8
! In 6/8, each beat is a dotted quarter (3 eighths)
! Verse (bars 1–8)
KG M6/8 ;;e    
g-a b--cb-     
a-f d--ef-     
g-e e--de-     
f-d b-e        
g-a b--cb-     
a-f d--ef-     
g--fe- #d--#cd-
e e            
! Refrain (bars 9–16)
KD ^d d--cb-   
a-f d--ef-     
g-e e--de-     
f-d b          
^d d--cb-      
a-f d--ef-     
g--fe- #d--#cd-
e e            `
  },
  {
    title: 'Happy Birthday',
    filename: 'happy-birthday.dsl',
    content: `! Happy Birthday — Traditional
! Key: F major (1 flat) | Meter: 3/4 — pickup on beat 3
KF M3/4 
cc      
d c f   
e - cc  
d c ^g  
f - cc  
^c a f  
e d -   
^&bb a f
g f -   `
  },
  {
    title: 'Jingle Bells',
    filename: 'jingle-bells.dsl',
    content: `! Jingle Bells — James Lord Pierpont (1857)
! Key: C major  Meter: 4/4
! Chorus (bars 1–8)
ee e ee e       :L Jingle bells, jingle bells,
eg /c--d e -    :L jingle all the way
ff f--f fe e-ee :L O what fun it is to ride in a
ed de d g       :L one horse open sleigh. Hey!
ee e ee e       :L Jingle bells, jingle bells,
eg /c--d e -    :L jingle all the way
ff f--f fe e-ee :L O what fun it is to ride in a
gg fd c -g      :L one horse open sleigh. A
! Verse
g^e dc g -g     :L day or two ago I
g^e dc a -a     :L thought I'd take a ride and
a^f ed b -b     :L soon Miss Fanny Bright was
^gg fd e -/g    :L seated by my side.
g^e dc g -g     :L The horse was lean and lank. Mis
g^e dc a -a     :L fortune seemed his lot. We
a^f ed gg gg    :L got_in to_a drifted bank_and
ag fd c ^g      :L we,_we got_up sot. Oh!
ee e ee e       :L Jingle bells, jingle bells,
eg /c--d e -    :L jingle all the way
ff f--f fe e-ee :L O what fun it is to ride in a
ed de d g       :L one horse open sleigh. Hey!
ee e ee e       :L Jingle bells, jingle bells,
eg /c--d e -    :L jingle all the way
ff f--f fe e-ee :L O what fun it is to ride in a
gg fd c -       :L one horse open sleigh.`
  },
  {
    title: 'Minuet in G major',
    filename: 'minuet-in-g.dsl',
    content: `! Minuet in G major — BWV Anh. 114
! Composer: Christian Petzold (formerly attributed to J.S. Bach)
! Key: G major (1 sharp) | Meter: 3/4
KG M3/4 d /ga bc
d /g g          
^e cd ef        
g /g g          
c dc ba         
b cb ag         
f ga bg         
b a -           
d /ga bc        
d /g g          
^e cd ef        
g /g g          
c dc ba         
b cb ag         
a ba gf         
g - -           `
  },
  {
    title: 'Ode to Joy',
    filename: 'ode-to-joy.dsl',
    content: `! Ode to Joy — Theme from Symphony No. 9
! Composer: Ludwig van Beethoven
! Key: C major | Meter: 4/4
KC M4/4 e e f g
g f e d        
c c d e        
e -d d -       
e e f g        
g f e d        
c c d e        
d -c c -       
d d e c        
d ef e c       
d ef e d       
c d /g ^e      
- e f g        
g f e d        
c c d e        
d -c c -       `
  },
  {
    title: 'Stille Nacht',
    filename: 'stille-nacht.dsl',
    content: `K&E M3/4
b
e -
ee 2e-----b-
^ff 2f-----f-
ge c d
e - g
gf 2f-----f-
gf 2f-----f-
ge c f
/b - ^b
2f-----b- -
g ^e -
2e-----dc cbb&a
b - b
bagf 2f-----b-
cbag 2g-----^e-
2e-----dc cbb&a
b - b
2c-----c- c/d
fe e ^b
2c-----c- c/d
fe e -
^ed d -
fe e e
2e-----dc bagf
e - fe
`
  },
  {
    title: 'The Cuckoo',
    filename: 'the_cuckoo.dsl',
    content: `! The Cuckoo -- Traditional English
M6/8 ^c-b a-b :H C D :L Sum mer is a
c-c bag       :H C D :L com ing in**
e-e f-d       :H G F :L loud ly sing cu-
e ;           :H G ; :L koo. ;
c-e d-f       :H C D :L grow eth seed and
e-e d-c       :H C D :L blow eth mead and
e-g a-a       :H G F :L springs the wood a-
g ;           :H G ; :L new ;
c a           :H C D :L Sing cu-
c ;           :H C D :L koo ;
g-e f-d       :H G F :L ewes are bleat ing
e-g f-e       :H G ; :L af ter lambs and
c-e d-b       :H C D :L cows are low ing
c ;           :H C D :L too ;
e-e d-f       :H G F :L bucks are snort ing
g-g a-b       :H G ; :L bulls ca vort ing
c-b a-b       :H C D :L Mer ry sing cu-
c ;           :H C D :L koo ;
g a           :H G F :L Sing cu-
g f           :H G ; :L koo now!
c-e f-d       :H C D :L Well sing est thou
e f-a         :H C D :L cu koo, and
e-g d-b       :H G F :L I can sing it
c ;           :H G ; :L too. ;
`
  },
  {
    title: 'Three Blind Mice',
    filename: 'three-blind-mice.dsl',
    content: `! Three Blind Mice — Traditional English Nursery Rhyme
! Key: C major | Meter: 4/4
KC M4/4 e d c -    :L Three blind mice -
e d c -            :L three blind mice -
^g f--f e -        :L See how they run, -
g f--f e g         :L see how they run. - They
c--c bab c--g g--g :L all ran after the farmer's wife. She
ccc bab c--g g--g  :L She cut off their tails with a carving knife, did
ccc bab cgg g--f   :L ever you see such a thing in your life as
e d c -            :L three blind mice?`
  },
  {
    title: 'Twinkle Twinkle Little Star',
    filename: 'twinkle-twinkle.dsl',
    content: `! Twinkle Twinkle Little Star — Traditional
! Key: C major | Meter: 4/4
c c ^g g :H C - G - :L Twinkle, twinkle
a a g -  :H F - C - :L little star.
f f e e  :H F - C - :L How I won der
d d c -  :H G - C - :L what you are,
^g g f f :H C - F - :L up a bove the
e e d -  :H C - G - :L world so high,
g g f f  :H C - F - :L like a dia mond
e e d -  :H C - G - :L in the sky.
c c ^g g :H C - G - :L Twinkle, twinkle
a a g -  :H F - C - :L little star.
f f e e  :H F - C - :L How I won der
d d c -  :H G - C - :L what you are,`
  },
];
